force-app/main/default/objects/Airtable_Configuration__mdt/Airtable_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Airtable Configuration</label>
    <pluralLabel>Airtable Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Airtable_Configuration__mdt/fields/Base_Path__c.field-meta.xml
<CustomField>
    <fullName>Base_Path__c</fullName>
    <label>Base Path</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Airtable_Table__mdt/Airtable_Table__mdt.object-meta.xml
<CustomObject>
    <label>Airtable Table</label>
    <pluralLabel>Airtable Tables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Airtable_Table__mdt/fields/Table_Id__c.field-meta.xml
<CustomField>
    <fullName>Table_Id__c</fullName>
    <label>Table Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AirtableSelector.cls
public with sharing class AirtableSelector {
  public static String getTableId(String tableName) {
    List<Airtable_Table__mdt> table = [
      SELECT DeveloperName, Table_Id__c
      FROM Airtable_Table__mdt
      WHERE DeveloperName = :tableName.toUpperCase()
      LIMIT 1
    ];
    if (table.isEmpty()) {
      throw new AirtableException('Table not found');
    }
    return table[0].Table_Id__c;
  }

  public static String getBasePath() {
    List<Airtable_Configuration__mdt> path = [
      SELECT DeveloperName, Base_Path__c
      FROM Airtable_Configuration__mdt
      WHERE DeveloperName = 'path'
      LIMIT 1
    ];
    if (path.isEmpty()) {
      throw new AirtableException('Path not found');
    }

    return path[0].Base_Path__c;
  }
}