force-app/main/default/objects/Airtable_Configuration__mdt/Airtable_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Airtable Configuration</label>
    <pluralLabel>Airtable Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Airtable_Configuration__mdt/fields/api_version__c.field-meta.xml
<CustomField>
    <fullName>api_version__c</fullName>
    <label>api version</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomMetadataUpdater.cls
/**
 * Created by malek on 2025-12-16.
 */

public with sharing class CustomMetadataUpdater {
    public static void updateMetadata() {


        Metadata.CustomMetadata cmd = new Metadata.CustomMetadata();
        cmd.fullName = 'Airtable_Configuration__mdt.Airtable_configs';
        cmd.label = 'Airtable Configs';

        Metadata.CustomMetadataValue val = new Metadata.CustomMetadataValue();
        val.field = 'api_version__c';
        val.value = 'newVersion';

        cmd.values = new List<Metadata.CustomMetadataValue>{val};

        Metadata.DeployContainer container = new Metadata.DeployContainer();
        container.addMetadata(cmd);

        Id jobId = Metadata.Operations.enqueueDeployment(container, null);
        System.debug('Job Id: ' + jobId);
    }
}