force-app/main/default/objects/Airtable_Configuration__mdt/Airtable_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Airtable Configuration</label>
    <pluralLabel>Airtable Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Airtable_Configuration__mdt/fields/api_version__c.field-meta.xml
<CustomField>
    <fullName>api_version__c</fullName>
    <label>api version</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airtable_Configuration__mdt/fields/Base_Path__c.field-meta.xml
<CustomField>
    <fullName>Base_Path__c</fullName>
    <label>Base Path</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Airtable_Table__mdt/Airtable_Table__mdt.object-meta.xml
<CustomObject>
    <label>Airtable Table</label>
    <pluralLabel>Airtable Tables</pluralLabel>
</CustomObject>

force-app/main/default/objects/Airtable_Table__mdt/fields/Table_Id__c.field-meta.xml
<CustomField>
    <fullName>Table_Id__c</fullName>
    <label>Table Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Experience_Site_Setting__mdt/Experience_Site_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Experience Site Setting</label>
    <pluralLabel>Experience Site Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Experience_Site_Setting__mdt/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MetadataSelector.cls
public with sharing class MetadataSelector {
  public static String getAirtableTableId(String tableName) {
    List<Airtable_Table__mdt> table = [
      SELECT DeveloperName, Table_Id__c
      FROM Airtable_Table__mdt
      WHERE DeveloperName = :tableName.toUpperCase()
      LIMIT 1
    ];
    if (table.isEmpty()) {
      throw new AirtableException('Table not found');
    }
    return table[0].Table_Id__c;
  }

  public static AirtableConfig getAirtableBasePath() {
    List<Airtable_Configuration__mdt> configs = [
      SELECT DeveloperName, Base_Path__c, api_version__c
      FROM Airtable_Configuration__mdt
      WHERE DeveloperName = 'Airtable_configs'
      LIMIT 1
    ];
    if (configs.isEmpty()) {
      throw new AirtableException('Path not found');
    }
    AirtableConfig configsWrapper = new AirtableConfig();
    configsWrapper.url = configs[0].Base_Path__c;
    configsWrapper.apiVersion = configs[0].api_version__c;
    return configsWrapper;
  }

  public static String getGuestSiteUrl() {
    List<Experience_Site_Setting__mdt> url = [
      SELECT url__c
      FROM Experience_Site_Setting__mdt
      WHERE DeveloperName = 'Guest_Site'
      LIMIT 1
    ];
    if (url.isEmpty()) {
      throw new AirtableException('Url not found');
    } else {
      return url[0].url__c;
    }
  }

  public class AirtableConfig {
    public String url;
    public String apiVersion;
  }
}